//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelYonetimSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int id { get; set; }
        public Nullable<int> departmanID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<short> maas { get; set; }
        public Nullable<System.DateTime> dTarihi { get; set; }
        public bool cinsiyet { get; set; }
        public bool medeniHal { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
